#include QMK_KEYBOARD_H


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT(QK_GESC, KC_Q, KC_W, KC_F, KC_P, KC_B, KC_J, KC_L, KC_U, KC_Y, KC_SCLN, KC_DEL, KC_TAB, KC_A, KC_R, KC_S, KC_T, KC_G, KC_M, KC_N, KC_E, KC_I, KC_O, KC_BSPC, OSM(MOD_LSFT), KC_X, KC_C, KC_D, KC_Z, KC_V, KC_HOME, TG(1), MO(4), TG(3), KC_K, KC_H, KC_TRNS, KC_DOT, KC_SLSH, KC_ENT, OSM(MOD_LALT), KC_CAPS, KC_LGUI, MO(1), KC_LCTL, TG(4), LT(3,OSM(MOD_RALT)), RALT_T(KC_SPC), MO(5), MO(2)),
	[1] = LAYOUT(TG(6), SGUI(KC_1), SGUI(KC_2), SGUI(KC_3), SGUI(KC_4), SGUI(KC_5), KC_PGUP, KC_HOME, KC_UP, KC_END, LGUI(KC_PGUP), KC_DEL, TG(7), RGUI(KC_1), RGUI(KC_2), RGUI(KC_3), RGUI(KC_4), RGUI(KC_5), KC_PGDN, KC_LEFT, KC_DOWN, KC_RGHT, LGUI(KC_PGDN), KC_BSPC, KC_NO, KC_LGUI, KC_LSFT, KC_LCTL, KC_LALT, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_NO, KC_F12, TG(0), KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_NO),
	[2] = LAYOUT(KC_NO, KC_NO, KC_BTN1, KC_MS_U, KC_BTN2, KC_WH_U, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_MS_L, KC_MS_D, KC_MS_R, KC_WH_D, SGUI(KC_PGUP), KC_MUTE, KC_VOLD, KC_VOLU, KC_BRIU, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, SGUI(KC_PGDN), KC_MPRV, KC_MPLY, KC_TRNS, KC_BRID, KC_PSCR, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_NO, KC_TRNS),
	[3] = LAYOUT(KC_ESC, LALT(KC_TAB), LCTL(KC_X), LCTL(KC_C), LCTL(KC_V), LALT(KC_ENT), KC_PGUP, KC_HOME, KC_UP, KC_END, KC_NO, KC_DEL, KC_TAB, KC_LGUI, KC_LALT, KC_LSFT, KC_LCTL, KC_APP, KC_PGDN, KC_LEFT, KC_DOWN, KC_RGHT, LCTL(KC_SLSH), KC_BSPC, TG(0), KC_F12, KC_WREF, KC_WBAK, KC_WFWD, LCA(KC_B), TG(0), KC_NO, KC_NO, KC_TRNS, LCTL(KC_B), LCTL(KC_H), KC_LCTL, MO(10), LCTL(KC_DOT), KC_ENT, KC_NO, KC_NO, KC_NO, MO(1), KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_NO, KC_NO),
	[4] = LAYOUT(KC_ESC, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_7, KC_8, KC_9, KC_NO, KC_DEL, KC_TAB, KC_PPLS, KC_PAST, KC_PMNS, KC_PSLS, KC_NO, KC_0, KC_4, KC_5, KC_6, KC_NO, KC_BSPC, KC_NO, KC_NO, KC_PCMM, KC_PDOT, KC_PEQL, KC_NO, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_1, KC_2, KC_3, KC_NO, KC_ENT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, MO(3), KC_SPC, KC_0, KC_PDOT),
	[5] = LAYOUT(KC_GRV, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_PSCR, KC_SLSH, KC_BSLS, KC_COLN, KC_LT, KC_GT, KC_NO, LSFT(KC_8), KC_LPRN, KC_LCBR, KC_LBRC, KC_MINS, KC_BSPC, KC_LSFT, KC_NO, KC_QUOT, KC_DQUO, LSFT(KC_BSLS), KC_AMPR, TG(0), KC_NO, KC_NO, KC_NO, LSFT(KC_2), KC_RPRN, KC_RCBR, KC_RBRC, KC_EQL, KC_ENT, KC_NO, KC_NO, KC_LALT, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_NO, KC_NO),
	[6] = LAYOUT(KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_BSPC, KC_LCTL, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT, KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B, TO(0), KC_NO, KC_COMM, KC_DOT, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_RSFT, KC_NO, KC_LGUI, KC_ENT, KC_SPC, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO),
	[7] = LAYOUT(KC_ESC, KC_TAB, KC_Q, KC_W, KC_E, KC_T, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_DEL, KC_TRNS, KC_LSFT, KC_A, KC_S, KC_D, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_BSPC, KC_NO, KC_LCTL, KC_NO, KC_NO, KC_NO, KC_NO, TO(0), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_ENT, KC_NO, KC_NO, KC_NO, KC_SPC, KC_NO, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_NO),
	[8] = LAYOUT(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_NO),
	[9] = LAYOUT(LCTL(KC_ESC), LCTL(KC_E), LALT(KC_F12), LCTL(KC_G), LCTL(KC_P), LCTL(KC_O), LALT(KC_F9), LSFT(KC_F10), LALT(KC_4), KC_NO, KC_NO, KC_NO, RALT(KC_TAB), LCA(KC_W), LCTL(KC_X), LCTL(KC_C), LCTL(KC_V), LCTL(KC_K), LCTL(KC_N), LCTL(KC_L), LSA(KC_UP), KC_NO, KC_NO, KC_NO, LCTL(KC_GRV), LCTL(KC_D), LCTL(KC_F), LCTL(KC_R), LCTL(KC_Z), LCA(KC_COMM), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, LSA(KC_DOWN), KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO),
	[10] = LAYOUT(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO)
};

/**
    encoder func
 */
bool encoder_update_user(uint8_t index, bool clockwise) {
    if (get_highest_layer(layer_state|default_layer_state) == 10){
      if (index == 0) { /* First encoder */
         if (clockwise) {
           tap_code16(KC_UP);
           tap_code16(KC_UP);
           tap_code16(KC_UP);
           tap_code16(KC_UP);
         } else {
           tap_code16(KC_DOWN);
           tap_code16(KC_DOWN);
           tap_code16(KC_DOWN);
           tap_code16(KC_DOWN);
         }
      }
    }else if (get_highest_layer(layer_state|default_layer_state) > 0) {
        if (index == 0) { /* First encoder */
           if (clockwise) {
             tap_code16(KC_RIGHT);
           } else {
             tap_code16(KC_LEFT);
           }
        }
    }else {
      if (index == 0) { /* First encoder */
             if (clockwise) {
               tap_code16(KC_UP);
             } else {
               tap_code16(KC_DOWN);
             }
          }
    }
  return false;
}
